version: "3"

services:
  frontend:
    build: ./client
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
    volumes:
      - ./client:/home/node/app
      - /home/node/app/node_modules

  api:
    build: ./api
    command: ["yarn", "dev"]
    ports:
      - "5000:5000"
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules